port: 4222
http_port: 8222

websocket {
  port: 8080
  no_tls: true
}

authorization {
  auth_callout {
    issuer: $NATS_ACCOUNT_SIGNER_PUBLIC_KEY
    account: AUTH
    auth_users: [ $NATS_AUTH_USER ]
  }
}

accounts {
  AUTH: {
    users: [
      {
        user: $NATS_AUTH_USER
        password: $NATS_AUTH_PASSWORD
      }
    ]
  }
  APP: {}
  SYS: {}
}

system_account: SYS
