port: 4222
http_port: 8222

authorization {
  users: [
    {
      user: $NATS_BACKEND_USER
      password: $NATS_BACKEND_PASSWORD
      permissions: {
        publish: { allow: ["app.>"] }
        subscribe: { allow: ["app.>"] }
      }
    }
  ]
}
